package com.gymapp.android.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFFFF5722)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFCCBC)
val md_theme_light_onPrimaryContainer = Color(0xFF3D1A0A)
val md_theme_light_secondary = Color(0xFF546E7A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1A1A1A)
val md_theme_light_surface = Color(0xFFF8F9FA)
val md_theme_light_onSurface = Color(0xFF1A1A1A)
val md_theme_light_surfaceVariant = Color(0xFFF1F3F4)
val md_theme_light_onSurfaceVariant = Color(0xFF5F6368)
val md_theme_light_outline = Color(0xFFDADCE0)
val md_theme_light_outlineVariant = Color(0xFFEBEBEB)
val md_theme_light_error = Color(0xFFD93025)
val md_theme_light_onError = Color(0xFFFFFFFF)

// Dark Theme Colors (Kept but not used if forced to Light)
val md_theme_dark_primary = Color(0xFFFF5722)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF3D1A0A)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFCCBC)
val md_theme_dark_secondary = Color(0xFFB0BEC5)
val md_theme_dark_onSecondary = Color(0xFF0D0D0D)
val md_theme_dark_background = Color(0xFF0D0D0D)
val md_theme_dark_onBackground = Color(0xFFEDEDEC)
val md_theme_dark_surface = Color(0xFF1A1A1A)
val md_theme_dark_onSurface = Color(0xFFEDEDEC)
val md_theme_dark_surfaceVariant = Color(0xFF242424)
val md_theme_dark_onSurfaceVariant = Color(0xFF8A8F98)
val md_theme_dark_outline = Color(0xFF2E2E2E)
val md_theme_dark_outlineVariant = Color(0xFF1F1F1F)
val md_theme_dark_error = Color(0xFFE53935)
val md_theme_dark_onError = Color(0xFFFFFFFF)

val color_success = Color(0xFF4CAF50)
val color_warning = Color(0xFFFFC107)
